### ISSUE TITLE
Maps does not start under wayland (sway)

### ISSUE THREAD

**Issue by kennylevinsen** [flathub/org.gnome.Maps#10]
## Info

flatpak info org.gnome.Maps:

```
GNOME Maps - Find places around the world

          ID: org.gnome.Maps
         Ref: app/org.gnome.Maps/x86_64/stable
        Arch: x86_64
      Branch: stable
     License: GPL-2.0-or-later
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 22.8 MB
     Runtime: org.gnome.Platform/x86_64/3.32
         Sdk: org.gnome.Sdk/x86_64/3.32

      Commit: 4f8c2098f5cd6f7014d4bc32b82e56f318401ce4c143815f396513d7b5a879ea
      Parent: 771d1e205b0dc528d5ee5369a886f6fb735759fe76fd26603acf3461267bdeaa
     Subject: Update to 3.32 runtime and 3.32 Maps (25c5aa6f)
        Date: 2019-03-16 16:01:12 +0000
```

System: Arch

## Reproduction steps

Run org.gnome.Maps under sway

## Expected result

Maps should open.

## Actual result

Nothing. Application does not terminate, but does not print anything or open any windows.

## Logs

Only interesting thing from the journal would be:

```
Jun 01 01:21:53 lappy xdg-desktop-por[1240]: Failed to get application states: GDBus.Error:org.freedesktop.portal.Error.Failed: Could not get window list: Cannot invoke method; proxy is for the well-known name org.gnome.Shell without an owner, and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag
```

Not sure if related.

## Notes

Running the application with '-h' works, and setting GDK_BACKEND=X11 results in `cannot open display: :99.0`, so the binary is alive and well.

**Comment by apiraino** [comment]
For what it's worth, I also have this issue on Wayland and Sway 1.4 and `wlroots` 0.10.0

But Gnome does provide feedback for other than their desktop manager under Wayland (not being critical, just stating a fact)

**Comment by hadess** [comment]
Trying to run the X11 backend under wayland isn't going to work, the X11 socket is only accessible under X11:
https://github.com/flathub/org.gnome.Maps/blob/master/org.gnome.Maps.json#L9

> (org.gnome.Maps:24439): Clutter-Gtk-ERROR **: 16:58:11.362: *** Unsupported backend.

You also need to set the clutter backend.

The output of `flatpak run org.gnome.Maps` would be a minimum requirement.

**Comment by kennylevinsen** [comment]
After a brief revisit I found the problem: Clutter's wayland backend uses wl_shell, which is deprecated and no longer supported by a lot of compositors. The infinite loop might be an attempt to wait for wl_shell to be advertised. See https://gitlab.gnome.org/GNOME/clutter/-/merge_requests/5.

CLUTTER_BACKEND=wayland comes from a list of misinformed environment variables from e.g. the Arch Linux wiki. Not setting it, or setting CLUTTER_BACKEND=gdk does the trick. Closing as it is not a flatpak problem.

**Comment by hadess** [comment]
> CLUTTER_BACKEND=wayland comes from a list of misinformed environment variables from e.g. the Arch Linux wiki.

[Huh](https://gitlab.gnome.org/GNOME/clutter/blob/master/clutter/clutter-backend.c#L577)?

**Comment by hadess** [comment]
`wayland` isn't a valid clutter backend, granted, but that's not what I said to set it to ;)

**Comment by kennylevinsen** [comment]
> wayland isn't a valid clutter backend, granted, 

[It is](https://gitlab.gnome.org/GNOME/clutter/blob/master/clutter/clutter-backend.c#L549), but [as it uses the long deprecated wl_shell protocol](https://gitlab.gnome.org/GNOME/clutter/-/blob/master/clutter/wayland/clutter-backend-wayland.c#L149), it isn't functional on most compositors.

> but that's not what I said to set it to ;)

Oh, that's not what I was suggesting. I was referring to `CLUTTER_BACKEND=wayland` being suggested, incorrectly as it's unnecessary and broken on most compositors, by places such as the [Arch Linux wiki](https://wiki.archlinux.org/index.php/Wayland#Clutter).

There's a stack of environment variables that a lot of Wayland users carry around from wiki pages and the likes. `MOZ_ENABLE_WAYLAND=1`, `QT_QPA_PLATFORM=wayland`, `_JAVA_AWT_WM_NONREPARENTING=1`, ... They tend to be copied blindly, and occasionally contain harmful things like `GDK_BACKEND=wayland` (which apart from a temporary mistake in Firefox is a downgrade from the default, which tries wayland first if supported).

When I saw your mention of Clutter now, I remembered that it [doesn't yet support xdg_shell](https://gitlab.gnome.org/GNOME/clutter/-/merge_requests/5), checked my vars, and found `CLUTTER_BACKEND=wayland`. Once I unset it, or set it to `CLUTTER_BACKEND=gdk` instead, everything ran fine. I'd imagine that GNOME Maps was just the first and only Clutter application I've ever tried to use.
