### ISSUE TITLE
Remove NetworkManager access

### ISSUE THREAD

**Issue by hadess** [flathub/org.gnome.Maps#18]
Now that https://bugzilla.gnome.org/show_bug.cgi?id=777706 is fixed, direct access to NetworkManager shouldn't be needed:
https://github.com/flathub/org.gnome.Maps/blob/f7210abdb2f25267ef98c0af0fe819e89ee71ce0/org.gnome.Maps.json#L18

**Comment by mlundblad** [comment]
Thanks for noticing!
I also did the same change in the manifest in upstream master.
