### ISSUE TITLE
Maps not displaying any map tiles

### ISSUE THREAD

**Issue by mjog** [flathub/org.gnome.Maps#3]
I just replaced my copy of Maps from the Ubuntu package with Maps from Flathub, and it doesn't actually show any map tiles - just a grey window background.

Everything else (search, routing, etc) seems to work fine.

**Comment by mlundblad** [comment]
This is because our tile subscription with Mapbox has expired. See https://bugzilla.gnome.org/show_bug.cgi?id=794429

**Comment by mjog** [comment]
This was resolved a while ago. Closing.
