### ISSUE TITLE
No connection

### ISSUE THREAD

**Issue by jurf** [flathub/org.gnome.Maps#6]
Even after a87fa61412e916ad16b65146ebc324a90cbe8d1d.

F29 Beta, Silverblue, if that affects anything.

**Comment by Exalm** [comment]
Running it with 3.30 platform seems to fix it: `flatpak run --runtime=org.gnome.Platform//3.30 org.gnome.Maps`

So, hopefully, #7 will fix it.

**Comment by Maltimore** [comment]
No connection again after the last update fc55d4bd5 on Kubuntu 18.04

**Comment by Maltimore** [comment]
@nedrichards there's still no connection after fc55d4b

**Comment by Maltimore** [comment]
@jurf it's fixed for me after the most recent update to the gnome runtime.

**Comment by jurf** [comment]
Yeah, for me too.
